seed: 42
device: cuda
device_no: 2
print_freq: 30
output_dir: experiments_vanilla_cbm
dataset:
    name: gtsrb
    n_labels: 43
    n_concepts: 43
    batch_size: 64
    num_workers: 50
    shuffle_dataset: True
    pin_memory: True
    data_path: ../../../data/raw/GTSRB/converted
    val_split: 0.2
    concepts_file: ../../../data/raw/GTSRB/concepts/concepts_per_class.csv
concept_predictor:
    log_dir: logs
    checkpoint_dir: models
    lr: 0.0001
    epochs: 30
    lr_step: 10
    lr_gamma: 0.5
    early_stopping_patience: 5
    momentum: 0.9
    weight_decay: 10e-4
    freeze: False
    pretrained_weights: null
    criterion: bce_with_logits
    optimizer: adam
    scheduler: none
    fuzzy_loss:
        use_fuzzy_loss: False
label_predictor:
    log_dir: logs
    checkpoint_dir: models
    lr: 0.001
    epochs: 15
    lr_step: 10
    lr_gamma: 0.5
    early_stopping_patience: 5
    momentum: 0.9
    weight_decay: 5e-4
    freeze: True
    pretrained_weights: /vol/home-vol2/se/costajoa/Dokumente/trainFuzzy/files/models/gt_label_predictor/models/20251007_163247_label_predictor_best_model.pt
    criterion: cross_entropy
    optimizer: adam
    scheduler: reduce_on_plateau
    scheduler_params: 
        mode: min
        factor: 0.5
        patience: 5
        min_lr: 0.00001
